

CONNECT system/oracle;

CREATE USER ec IDENTIFIED BY tiger;

GRANT DBA TO ec;

/* ?��?�� */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 게시�? */
DROP TABLE POST 
	CASCADE CONSTRAINTS;

/* 좋아?�� */
DROP TABLE LIKE 
	CASCADE CONSTRAINTS;

/* ?���? */
DROP TABLE REPLY 
	CASCADE CONSTRAINTS;

/* 카테고리 */
DROP TABLE CATEGORY 
	CASCADE CONSTRAINTS;

/* 게시�??���? */
DROP TABLE POSTTAG 
	CASCADE CONSTRAINTS;

/* ?���? */
DROP TABLE TAG 
	CASCADE CONSTRAINTS;

/* 게시�??��?��???��?�� */
DROP TABLE IMG_DIRETORY 
	CASCADE CONSTRAINTS;

/* 게시�??��미�? */
DROP TABLE IMG 
	CASCADE CONSTRAINTS;

/* ?��?�� */
DROP TABLE PLANNER 
	CASCADE CONSTRAINTS;

/* 초�? */
DROP TABLE INVITE 
	CASCADE CONSTRAINTS;

/* ?���??��?�� */
DROP TABLE DETAIL_PLANNER 
	CASCADE CONSTRAINTS;

/* �?광�? */
DROP TABLE CONTENT 
	CASCADE CONSTRAINTS;

/* ??분류 */
DROP TABLE CAT1 
	CASCADE CONSTRAINTS;

/* 중분�? */
DROP TABLE CAT2 
	CASCADE CONSTRAINTS;

/* ?��분류 */
DROP TABLE CAT3 
	CASCADE CONSTRAINTS;

/* 콘텐츠�??�� */
DROP TABLE CONTENTTYPE 
	CASCADE CONSTRAINTS;

/* ?��?�� */
CREATE TABLE MEMBER (
	M_ID NUMBER NOT NULL, /* ?��?��ID */
	M_EMAIL VARCHAR2(40) NOT NULL, /* ?��메일 */
	M_PWD VARCHAR2(40) NOT NULL, /* 비�?번호 */
	M_GEN VARCHAR2(10) NOT NULL, /* ?���? */
	M_NNAME VARCHAR2(20) NOT NULL, /* ?��?��?�� */
	M_BIRTH DATE NOT NULL, /* ?��?��?��?�� */
	M_RDATE DATE, /* �??��?�� */
	M_IMAGE VARCHAR2(40), /* ?��로필?��미�? */
	M_STATUS NUMBER, /* ?��?��?��?�� */
	M_PROFIL NUMBER /* ?��?��?��?��로필 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		M_ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			M_ID
		);

/* 게시�? */
CREATE TABLE POST (
	P_ID NUMBER NOT NULL, /* 게시�?ID */
	M_ID NUMBER, /* ?��?��ID */
	C_ID NUMBER, /* 카테고리ID */
	P_CONTENT VARCHAR2(2000), /* �??��?�� */
	P_VIEWS NUMBER, /* 조회?�� */
	P_CREDATE DATE, /* ?��?��?�� */
	P_MODDATE DATE /* ?��?��?�� */
);

CREATE UNIQUE INDEX PK_POST
	ON POST (
		P_ID ASC
	);

ALTER TABLE POST
	ADD
		CONSTRAINT PK_POST
		PRIMARY KEY (
			P_ID
		);

/* 좋아?�� */
CREATE TABLE LIKE (
	L_ID NUMBER NOT NULL, /* 좋아?��ID */
	P_ID NUMBER, /* 게시�?ID */
	M_ID NUMBER, /* ?��?��ID */
	L_DATE DATE /* ?��록일 */
);

CREATE UNIQUE INDEX PK_LIKE
	ON LIKE (
		L_ID ASC
	);

ALTER TABLE LIKE
	ADD
		CONSTRAINT PK_LIKE
		PRIMARY KEY (
			L_ID
		);

/* ?���? */
CREATE TABLE REPLY (
	COL NUMBER NOT NULL, /* ?���?ID */
	M_ID NUMBER, /* ?��?��ID */
	P_ID NUMBER, /* 게시�?ID */
	R_CONTENT VARCHAR2(200) NOT NULL, /* �??��?�� */
	R_CREDATE DATE, /* ?��?��?�� */
	R_MODDATE DATE, /* ?��?��?�� */
	R_STATUS NUMBER /* ?���??��?�� */
);

CREATE UNIQUE INDEX PK_REPLY
	ON REPLY (
		COL ASC
	);

ALTER TABLE REPLY
	ADD
		CONSTRAINT PK_REPLY
		PRIMARY KEY (
			COL
		);

/* 카테고리 */
CREATE TABLE CATEGORY (
	C_ID NUMBER NOT NULL, /* 카테고리ID */
	C_NAME VARCHAR2(40) /* 카테고리�? */
);

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		C_ID ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			C_ID
		);

/* 게시�??���? */
CREATE TABLE POSTTAG (
	PT_ID NUMBER NOT NULL, /* 게시�??��그ID */
	P_ID NUMBER NOT NULL, /* 게시�?ID */
	T_ID NUMBER NOT NULL /* ?��그ID */
);

CREATE UNIQUE INDEX PK_POSTTAG
	ON POSTTAG (
		PT_ID ASC
	);

ALTER TABLE POSTTAG
	ADD
		CONSTRAINT PK_POSTTAG
		PRIMARY KEY (
			PT_ID
		);

/* ?���? */
CREATE TABLE TAG (
	T_ID NUMBER NOT NULL, /* ?��그ID */
	T_NAME VARCHAR2(40) NOT NULL /* ?��그이�? */
);

CREATE UNIQUE INDEX PK_TAG
	ON TAG (
		T_ID ASC
	);

ALTER TABLE TAG
	ADD
		CONSTRAINT PK_TAG
		PRIMARY KEY (
			T_ID
		);

/* 게시�??��?��???��?�� */
CREATE TABLE IMG_DIRETORY (
	DIR_ID NUMBER NOT NULL, /* ???��?��ID */
	P_ID NUMBER, /* 게시�?ID */
	I_ID NUMBER, /* ?��미�?ID */
	DIR_NUM NUMBER /* ?��미�??��?�� */
);

CREATE UNIQUE INDEX PK_IMG_DIRETORY
	ON IMG_DIRETORY (
		DIR_ID ASC
	);

ALTER TABLE IMG_DIRETORY
	ADD
		CONSTRAINT PK_IMG_DIRETORY
		PRIMARY KEY (
			DIR_ID
		);

/* 게시�??��미�? */
CREATE TABLE IMG (
	I_ID NUMBER NOT NULL, /* ?��미�?ID */
	I_PATH VARCHAR2(100), /* ?��미�?경로 */
	I_BIRTH DATE, /* ?��?��?�� */
	I_NAME VARCHAR2(100), /* ?��미�??���? */
	I_NAME2 VARCHAR2(10) /* ?��미�??��?��?�� */
);

CREATE UNIQUE INDEX PK_IMG
	ON IMG (
		I_ID ASC
	);

ALTER TABLE IMG
	ADD
		CONSTRAINT PK_IMG
		PRIMARY KEY (
			I_ID
		);

/* ?��?�� */
CREATE TABLE PLANNER (
	P_ID NUMBER NOT NULL, /* ?��?��ID */
	M_ID NUMBER, /* ?��?��ID */
	P_NAME VARCHAR2(20) NOT NULL, /* ?��?��?���? */
	P_BIRTH DATE, /* ?��?��?�� */
	P_MODDATE DATE /* ?��?��?�� */
);

CREATE UNIQUE INDEX PK_PLANNER
	ON PLANNER (
		P_ID ASC
	);

ALTER TABLE PLANNER
	ADD
		CONSTRAINT PK_PLANNER
		PRIMARY KEY (
			P_ID
		);

/* 초�? */
CREATE TABLE INVITE (
	I_ID NUMBER NOT NULL, /* 초�?ID */
	P_ID NUMBER, /* ?��?��ID */
	M_ID NUMBER, /* ?��?��ID */
	I_PER NUMBER, /* 권한 */
	I_STATUS NUMBER /* 초�??��?�� */
);

CREATE UNIQUE INDEX PK_INVITE
	ON INVITE (
		I_ID ASC
	);

ALTER TABLE INVITE
	ADD
		CONSTRAINT PK_INVITE
		PRIMARY KEY (
			I_ID
		);

/* ?���??��?�� */
CREATE TABLE DETAIL_PLANNER (
	DP_ID NUMBER NOT NULL, /* ?���??��?��ID */
	P_ID NUMBER, /* ?��?��ID */
	CONTENTID VARCHAR2(200), /* �?광�?ID */
	DP_DAY NUMBER, /* ?���? */
	DP_START DATE, /* ?��?��?��?��?�� */
	DP_END DATE, /* ?��?��종료?�� */
	DP_NUM NUMBER /* ?��?��?��?�� */
);

CREATE UNIQUE INDEX PK_DETAIL_PLANNER
	ON DETAIL_PLANNER (
		DP_ID ASC
	);

ALTER TABLE DETAIL_PLANNER
	ADD
		CONSTRAINT PK_DETAIL_PLANNER
		PRIMARY KEY (
			DP_ID
		);

/* �?광�? */
CREATE TABLE CONTENT (
	CONTENTID VARCHAR2(200) NOT NULL, /* �?광�?ID */
	CONTENTTYPEID VARCHAR2(20), /* 콘텐츠�??��ID */
	CAT3 VARCHAR2(20), /* ?��분류ID */
	TITLE VARCHAR2( 200), /* ?���? */
	TEL VARCHAR2( 200), /* ?��?��번호 */
	ADDR VARCHAR2( 400), /* 주소 */
	FIRSTIMAGE VARCHAR2( 600), /* ?��미�? */
	MAPX VARCHAR2( 200), /* 경도 */
	MAPY VARCHAR2( 200) /* ?��?�� */
);

CREATE UNIQUE INDEX PK_CONTENT
	ON CONTENT (
		CONTENTID ASC
	);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT PK_CONTENT
		PRIMARY KEY (
			CONTENTID
		);

/* ??분류 */
CREATE TABLE CAT1 (
	CAT1 VARCHAR2(20) NOT NULL, /* ??분류ID */
	CAT1_NAME VARCHAR2(200) /* ??분류?���? */
);

CREATE UNIQUE INDEX PK_CAT1
	ON CAT1 (
		CAT1 ASC
	);

ALTER TABLE CAT1
	ADD
		CONSTRAINT PK_CAT1
		PRIMARY KEY (
			CAT1
		);

/* 중분�? */
CREATE TABLE CAT2 (
	CAT2 VARCHAR2(20) NOT NULL, /* 중분류ID */
	CAT1 VARCHAR2(20), /* ??분류ID */
	CAT2_NAME VARCHAR2( 200) /* 중분류이�? */
);

CREATE UNIQUE INDEX PK_CAT2
	ON CAT2 (
		CAT2 ASC
	);

ALTER TABLE CAT2
	ADD
		CONSTRAINT PK_CAT2
		PRIMARY KEY (
			CAT2
		);

/* ?��분류 */
CREATE TABLE CAT3 (
	CAT3 VARCHAR2(20) NOT NULL, /* ?��분류ID */
	CAT2 VARCHAR2(20), /* 중분류ID */
	CAT3_NAME VARCHAR2(200) /* ?��분류?���? */
);

CREATE UNIQUE INDEX PK_CAT3
	ON CAT3 (
		CAT3 ASC
	);

ALTER TABLE CAT3
	ADD
		CONSTRAINT PK_CAT3
		PRIMARY KEY (
			CAT3
		);

/* 콘텐츠�??�� */
CREATE TABLE CONTENTTYPE (
	CONTENTTYPEID VARCHAR2(20) NOT NULL, /* 콘텐츠�??��ID */
	CT_NAME VARCHAR2(200) /* ???���? */
);

CREATE UNIQUE INDEX PK_CONTENTTYPE
	ON CONTENTTYPE (
		CONTENTTYPEID ASC
	);

ALTER TABLE CONTENTTYPE
	ADD
		CONSTRAINT PK_CONTENTTYPE
		PRIMARY KEY (
			CONTENTTYPEID
		);

ALTER TABLE POST
	ADD
		CONSTRAINT FK_MEMBER_TO_POST
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE POST
	ADD
		CONSTRAINT FK_CATEGORY_TO_POST
		FOREIGN KEY (
			C_ID
		)
		REFERENCES CATEGORY (
			C_ID
		);

ALTER TABLE LIKE
	ADD
		CONSTRAINT FK_POST_TO_LIKE
		FOREIGN KEY (
			P_ID
		)
		REFERENCES POST (
			P_ID
		);

ALTER TABLE LIKE
	ADD
		CONSTRAINT FK_MEMBER_TO_LIKE
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_REPLY
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_POST_TO_REPLY
		FOREIGN KEY (
			P_ID
		)
		REFERENCES POST (
			P_ID
		);

ALTER TABLE POSTTAG
	ADD
		CONSTRAINT FK_POST_TO_POSTTAG
		FOREIGN KEY (
			P_ID
		)
		REFERENCES POST (
			P_ID
		);

ALTER TABLE POSTTAG
	ADD
		CONSTRAINT FK_TAG_TO_POSTTAG
		FOREIGN KEY (
			T_ID
		)
		REFERENCES TAG (
			T_ID
		);

ALTER TABLE IMG_DIRETORY
	ADD
		CONSTRAINT FK_POST_TO_IMG_DIRETORY
		FOREIGN KEY (
			P_ID
		)
		REFERENCES POST (
			P_ID
		);

ALTER TABLE IMG_DIRETORY
	ADD
		CONSTRAINT FK_IMG_TO_IMG_DIRETORY
		FOREIGN KEY (
			I_ID
		)
		REFERENCES IMG (
			I_ID
		);

ALTER TABLE PLANNER
	ADD
		CONSTRAINT FK_MEMBER_TO_PLANNER
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE INVITE
	ADD
		CONSTRAINT FK_PLANNER_TO_INVITE
		FOREIGN KEY (
			P_ID
		)
		REFERENCES PLANNER (
			P_ID
		);

ALTER TABLE INVITE
	ADD
		CONSTRAINT FK_MEMBER_TO_INVITE
		FOREIGN KEY (
			M_ID
		)
		REFERENCES MEMBER (
			M_ID
		);

ALTER TABLE DETAIL_PLANNER
	ADD
		CONSTRAINT FK_PLANNER_TO_DETAIL_PLANNER
		FOREIGN KEY (
			P_ID
		)
		REFERENCES PLANNER (
			P_ID
		);

ALTER TABLE DETAIL_PLANNER
	ADD
		CONSTRAINT FK_CONTENT_TO_DETAIL_PLANNER
		FOREIGN KEY (
			CONTENTID
		)
		REFERENCES CONTENT (
			CONTENTID
		);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT FK_CAT3_TO_CONTENT
		FOREIGN KEY (
			CAT3
		)
		REFERENCES CAT3 (
			CAT3
		);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT FK_CONTENTTYPE_TO_CONTENT
		FOREIGN KEY (
			CONTENTTYPEID
		)
		REFERENCES CONTENTTYPE (
			CONTENTTYPEID
		);

ALTER TABLE CAT2
	ADD
		CONSTRAINT FK_CAT1_TO_CAT2
		FOREIGN KEY (
			CAT1
		)
		REFERENCES CAT1 (
			CAT1
		);

ALTER TABLE CAT3
	ADD
		CONSTRAINT FK_CAT2_TO_CAT3
		FOREIGN KEY (
			CAT2
		)
		REFERENCES CAT2 (
			CAT2
		);
        commit;
        
    create table cat3(
        code varchar2(200),
        name varchar2(200)
    );
    select * from cat3;
    create table cat3{
        CODE varchar2(200),
        NAME varchar2
    };
        